"""Google Colab cloud backend — runs models on Colab's free GPU.

Colab doesn't have a clean programmatic API like Kaggle. This backend works by:
1. Generating a self-contained Colab notebook (.ipynb)
2. Opening it in the user's browser
3. The notebook auto-runs: downloads input from a temp URL, runs the model,
   and provides a download link for results.

For fully automated (no-browser) execution, the user needs to set up
colab-connect or similar. This is the practical approach for free tier.
"""

import json
import time
import webbrowser
from pathlib import Path
from http.server import HTTPServer, SimpleHTTPRequestHandler
import threading

from rich.console import Console

console = Console()


def _create_notebook(model_name: str, input_filename: str, server_port: int) -> dict:
    """Generate a Colab notebook that runs inference."""
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# pixo Cloud Run\\n",
                f"Running **{model_name}** on `{input_filename}`\\n",
                "This notebook was generated by pixo. Just click **Runtime > Run all**.\\n",
            ],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "# Step 1: Install dependencies\\n",
                "!pip install ultralytics --quiet\\n",
            ],
            "execution_count": None,
            "outputs": [],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "# Step 2: Download input file from your local pixo server\\n",
                f'import urllib.request, os\\n',
                f'url = "http://localhost:{server_port}/{input_filename}"\\n',
                f'input_path = "/content/{input_filename}"\\n',
                '# Note: This only works if your local machine is accessible.\\n',
                '# For remote execution, upload the file to Google Drive instead.\\n',
                'try:\\n',
                '    urllib.request.urlretrieve(url, input_path)\\n',
                '    print(f"Downloaded {input_path}")\\n',
                'except Exception as e:\\n',
                '    print(f"Could not download from local server: {e}")\\n',
                '    print("Please upload the file manually using the sidebar.")\\n',
                '    from google.colab import files\\n',
                '    uploaded = files.upload()\\n',
                '    input_path = "/content/" + list(uploaded.keys())[0]\\n',
            ],
            "execution_count": None,
            "outputs": [],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "# Step 3: Run model\\n",
                "from ultralytics import YOLO\\n",
                'model = YOLO("yolov8n.pt")\\n',
                "results = model.predict(\\n",
                '    source=input_path,\\n',
                '    save=True,\\n',
                '    project="/content/pixo_output",\\n',
                '    name="results",\\n',
                "    exist_ok=True,\\n",
                ")\\n",
                "\\n",
                "# Print summary\\n",
                'if hasattr(results, "__len__"):\\n',
                "    total = sum(len(r.boxes) for r in results)\\n",
                '    print(f"Objects detected: {total}")\\n',
                'print("Done! Results are in /content/pixo_output/results/")\\n',
            ],
            "execution_count": None,
            "outputs": [],
        },
        {
            "cell_type": "code",
            "metadata": {},
            "source": [
                "# Step 4: Download results\\n",
                "import shutil, os\\n",
                '\\n',
                '# Zip results for easy download\\n',
                'shutil.make_archive("/content/pixo_results", "zip", "/content/pixo_output/results")\\n',
                "\\n",
                "from google.colab import files\\n",
                'files.download("/content/pixo_results.zip")\\n',
                'print("Results downloaded!")\\n',
            ],
            "execution_count": None,
            "outputs": [],
        },
    ]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 0,
        "metadata": {
            "colab": {
                "name": f"pixo-{model_name}-run",
                "provenance": [],
            },
            "kernelspec": {
                "name": "python3",
                "display_name": "Python 3",
            },
            "accelerator": "GPU",
        },
        "cells": cells,
    }
    return notebook


def run_on_colab(
    input_path: Path,
    output_dir: Path,
    model_name: str,
) -> dict:
    """Generate a Colab notebook and open it in the browser.

    This is semi-automated: pixo generates the notebook and opens it,
    but the user clicks 'Run all' in Colab and downloads results manually.
    """
    server_port = 18765
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate notebook
    notebook = _create_notebook(model_name, input_path.name, server_port)
    notebook_path = output_dir / f"pixo_{model_name}_run.ipynb"
    notebook_path.write_text(json.dumps(notebook, indent=2))

    console.print(f"[bold]Generated Colab notebook:[/bold] {notebook_path}")
    console.print()
    console.print("[bold]To run on Colab's free GPU:[/bold]")
    console.print("  1. Go to https://colab.research.google.com")
    console.print(f"  2. Upload the notebook: [cyan]{notebook_path}[/cyan]")
    console.print("  3. Click [bold]Runtime > Change runtime type > GPU[/bold]")
    console.print("  4. Click [bold]Runtime > Run all[/bold]")
    console.print("  5. Upload your input file when prompted")
    console.print("  6. Results will auto-download as a zip")
    console.print()

    # Try to open in browser
    try:
        webbrowser.open("https://colab.research.google.com/#create=true")
        console.print("[dim]Opened Colab in your browser.[/dim]")
    except Exception:
        pass

    return {
        "backend": "colab",
        "notebook_path": str(notebook_path),
        "status": "notebook_generated",
    }
